### ISSUE TITLE
Client Crash fabric-1.18.2-16.0.0

### ISSUE THREAD

**Issue by dirtyfargo** [LukeGrahamLandry/Torcherino#2]
Version: 16.0.0
Fabric: 0.14.8
FabricAPI: 0.56.1

Hi,

I am receiving the following client crash after adding Torcherino:

[crash-2022-06-22_10.24.36-client.txt](https://gist.github.com/dirtyfargo/87b01f0b4b741aa36e57cbc573c4f07e)

Thank you : )

**Comment by LukeGrahamLandry** [comment]
Thanks for reporting. 
I think this (16.0.1) should fix it but I'm not sure which mod added the mixin that conflicted (couldn't reproduce crash with only 16.0.0) so I can't test it myself. Let me know if this helps and I'll release the updated version. 

https://github.com/LukeGrahamLandryMC/Torcherino/releases/tag/16.0.1

**Comment by dirtyfargo** [comment]
Yes that fixed it, seems to work great now thank you! :)
