### ISSUE TITLE
1.18.2 Crash: java.lang.reflect.InvocationTargetExeption: null

### ISSUE THREAD

**Issue by heavenlygamer04** [LukeGrahamLandry/Torcherino#7]
Game crashes on boot for minecraft 1.18.2(mod version:16.0.1): java.lang.reflect.InvocationTargetExeption: null

here is the crash log 
[crash-2022-11-01_01.06.53-fml.txt](https://github.com/LukeGrahamLandry/Torcherino/files/9907039/crash-2022-11-01_01.06.53-fml.txt)

**Comment by LukeGrahamLandry** [comment]
possible that you (or your modpack) changed `config/sci4me/Torcherino.cfg` in a way it doesn't like (made it not a valid json object)? can I see that file?

// TODO: config loading should gracefully warn about json parsing issues and revert to the default config

**Comment by heavenlygamer04** [comment]
> 

i fixed the issue, it was reading the config from 1.12.2, so i deleted it and it works now. i didnt think that would be an issue. lol. thanks! 

sorry for bothering you over something stupid.
